/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:57:00 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterHelpAppendable_ESTest extends FilterHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) null, 0, 0);
      assertEquals(3, textHelpAppendable1.getIndent());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn((CharSequence) null).when(charSequence0).subSequence(anyInt() , anyInt());
      // Undeclared exception!
      try { 
        textHelpAppendable0.append(charSequence0, 766, (-590));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.PrintStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        textHelpAppendable0.append(charSequence0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('M');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append('h');
      assertEquals(1, TextHelpAppendable.DEFAULT_LEFT_PAD);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "=0iA%", 7, 1);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(charSequence0).toString();
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append(charSequence0);
      assertEquals(3, textHelpAppendable1.getIndent());
  }
}
