/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 08:00:33 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.util.List;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Iterable<List<String>> iterable0 = (Iterable<List<String>>) mock(Iterable.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(iterable0).toString();
      TableDefinition tableDefinition0 = TableDefinition.from("1Y bJk#g:D{Cc", (List<TextStyle>) null, (List<String>) null, iterable0);
      Iterable<List<String>> iterable1 = tableDefinition0.rows();
      assertSame(iterable1, iterable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("y ", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("y ", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertEquals("y ", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("y ", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TableDefinition tableDefinition0 = TableDefinition.from("y ", (List<TextStyle>) null, (List<String>) null, (Iterable<List<String>>) null);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }
}
