/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:43:15 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TextStyle_ESTest extends TextStyle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      textStyle_Builder0.setIndent((-1));
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setMaxWidth(895);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder3.get();
      textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      // Undeclared exception!
      try { 
        textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setMaxWidth(895);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      textStyle_Builder1.setScalable(true);
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle_Builder3.setMaxWidth(272);
      textStyle0.toString();
      textStyle_Builder5.getIndent();
      textStyle1.getLeftPad();
      textStyle0.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      boolean boolean0 = true;
      char[] charArray0 = new char[3];
      charArray0[0] = '[';
      textStyle0.toString();
      charArray0[1] = 'p';
      charArray0[2] = '@';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      charBuffer1.get();
      charBuffer0.get();
      // Undeclared exception!
      try { 
        textStyle0.DEFAULT.pad(true, charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.DEFAULT.toString();
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder2.setTextStyle(textStyle0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder3 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder2.get();
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder2.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder1.setScalable(true);
      textStyle_Builder1.setIndent(0);
      textStyle_Builder2.setMaxWidth((-1));
      textStyle_Builder2.setMaxWidth(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder4.getIndent();
      textStyle_Builder5.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      textStyle0.DEFAULT.toString();
      textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.RIGHT;
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder2 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      TextStyle textStyle1 = textStyle_Builder1.get();
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder2.setLeftPad(895);
      TextStyle.Alignment.values();
      textStyle_Builder1.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder0.setTextStyle(textStyle0);
      textStyle_Builder2.setLeftPad(895);
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder0.setScalable(true);
      textStyle1.DEFAULT.toString();
      textStyle_Builder3.setLeftPad(Integer.MAX_VALUE);
      textStyle_Builder1.setMaxWidth((-1));
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setMaxWidth(257);
      textStyle_Builder5.setScalable(true);
      textStyle_Builder0.setLeftPad(257);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder4.getIndent();
      textStyle1.toString();
      textStyle_Builder5.setTextStyle(textStyle0);
      textStyle1.getAlignment();
      textStyle0.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder0.setMinWidth(895);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setIndent(Integer.MAX_VALUE);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder5 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder4.get();
      TextStyle.Builder textStyle_Builder6 = textStyle_Builder5.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder4.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder7 = textStyle_Builder1.setScalable(true);
      textStyle_Builder2.setIndent(0);
      textStyle_Builder4.setMaxWidth((-1));
      textStyle_Builder4.setMaxWidth(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder6.getIndent();
      textStyle_Builder7.setTextStyle(textStyle0);
      textStyle1.getLeftPad();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(0);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder6 = textStyle_Builder1.setScalable(true);
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle_Builder3.setMaxWidth(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder5.getIndent();
      textStyle_Builder6.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.DEFAULT.toString();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      TextStyle textStyle1 = textStyle_Builder0.get();
      textStyle1.toString();
      TextStyle.Builder textStyle_Builder2 = TextStyle.builder();
      textStyle_Builder1.setMinWidth(Integer.MAX_VALUE);
      textStyle0.getAlignment();
      textStyle0.getLeftPad();
      int int0 = TextStyle.UNSET_MAX_WIDTH;
      textStyle0.DEFAULT.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setIndent(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder3.setMaxWidth(0);
      textStyle_Builder4.setMinWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setLeftPad(0);
      TextStyle.Builder textStyle_Builder6 = TextStyle.builder();
      textStyle_Builder4.setLeftPad(Integer.MAX_VALUE);
      textStyle1.getMaxWidth();
      textStyle_Builder0.getMinWidth();
      TextStyle textStyle2 = textStyle_Builder1.get();
      textStyle_Builder6.setTextStyle(textStyle1);
      textStyle_Builder4.setTextStyle(textStyle0);
      textStyle_Builder5.getMaxWidth();
      textStyle2.getLeftPad();
      textStyle0.getIndent();
      textStyle_Builder2.getMinWidth();
      textStyle2.getIndent();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getMaxWidth();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setIndent(Integer.MAX_VALUE);
      textStyle0.DEFAULT.toString();
      textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder3 = TextStyle.builder();
      textStyle_Builder3.setAlignment(textStyle_Alignment0);
      TextStyle textStyle1 = textStyle_Builder2.get();
      textStyle_Builder3.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder2.getMaxWidth();
      // Undeclared exception!
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(0);
      textStyle_Builder0.setMinWidth((-2081));
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder1.setIndent((-2081));
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.toString();
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder6 = textStyle_Builder1.setScalable(true);
      textStyle1.DEFAULT.toString();
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle_Builder3.setMaxWidth(272);
      textStyle_Builder0.setLeftPad(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder5.getIndent();
      textStyle_Builder6.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getMaxWidth();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder4.setAlignment(textStyle_Alignment0);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder6 = textStyle_Builder1.setScalable(true);
      textStyle1.DEFAULT.toString();
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder3.setMaxWidth(272);
      textStyle_Builder0.setLeftPad(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder5.getIndent();
      textStyle_Builder6.setTextStyle(textStyle0);
      textStyle1.getAlignment();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textStyle_Builder1.setAlignment(textStyle_Alignment0);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setIndent((-1));
      textStyle_Builder1.setScalable(false);
      textStyle_Builder1.setIndent((-2616));
      TextStyle textStyle0 = textStyle_Builder0.get();
      textStyle_Builder1.setIndent((-2616));
      textStyle0.getLeftPad();
      textStyle_Builder2.getIndent();
      textStyle_Builder2.setLeftPad((-1));
      textStyle_Builder1.setMinWidth(0);
      textStyle0.getIndent();
      textStyle_Builder2.setLeftPad((-2616));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setScalable(false);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setLeftPad(0);
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setMaxWidth(0);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setAlignment(textStyle_Alignment0);
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setIndent(0);
      textStyle_Builder0.setMaxWidth(1);
      TextStyle textStyle0 = textStyle_Builder5.get();
      textStyle_Builder0.isScalable();
      TextStyle.builder();
      char[] charArray0 = new char[3];
      charArray0[0] = 'k';
      charArray0[1] = 'G';
      charArray0[2] = 'p';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 0, 1);
      textStyle0.pad(false, charBuffer0);
      textStyle0.getAlignment();
      // Undeclared exception!
      try { 
        TextStyle.Alignment.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = (-1852);
      textStyle_Builder0.setMinWidth((-1852));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setTextStyle(textStyle0);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setIndent(3029);
      TextStyle textStyle1 = textStyle_Builder2.get();
      textStyle_Builder2.setMaxWidth(0);
      TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.RIGHT;
      textStyle_Builder2.setAlignment(textStyle_Alignment0);
      TextStyle.Builder textStyle_Builder3 = TextStyle.builder();
      textStyle_Builder3.setLeftPad(0);
      textStyle1.getAlignment();
      textStyle_Builder0.getMaxWidth();
      textStyle_Builder3.isScalable();
      TextStyle.builder();
      TextStyle textStyle2 = textStyle_Builder1.get();
      textStyle_Builder1.setTextStyle(textStyle2);
      textStyle2.toString();
      textStyle2.getMaxWidth();
      textStyle_Builder2.setTextStyle(textStyle2);
      textStyle1.toString();
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:3029, true, min:0, max:unset}");
      TextStyle.Alignment.values();
      String string0 = "$VALUES";
      // Undeclared exception!
      try { 
        TextStyle.Alignment.valueOf("$VALUES");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant org.apache.commons.cli.help.TextStyle.Alignment.$VALUES
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.DEFAULT.toString();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      TextStyle textStyle1 = textStyle_Builder1.get();
      textStyle1.toString();
      TextStyle.Builder textStyle_Builder2 = TextStyle.builder();
      textStyle_Builder0.setTextStyle(textStyle1);
      textStyle0.getAlignment();
      textStyle0.getLeftPad();
      textStyle_Builder0.getIndent();
      textStyle0.DEFAULT.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setIndent(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder3.setMaxWidth(0);
      textStyle_Builder4.setMinWidth(0);
      textStyle_Builder0.setMinWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setLeftPad(0);
      TextStyle.builder();
      textStyle_Builder4.setLeftPad(Integer.MAX_VALUE);
      textStyle1.getMaxWidth();
      textStyle_Builder0.getMinWidth();
      TextStyle textStyle2 = textStyle_Builder1.get();
      TextStyle.builder();
      textStyle_Builder4.setTextStyle(textStyle0);
      textStyle_Builder5.getMaxWidth();
      textStyle2.getLeftPad();
      textStyle0.getIndent();
      textStyle_Builder2.getMinWidth();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(0);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder4.setAlignment(textStyle_Alignment0);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder6 = textStyle_Builder1.setScalable(true);
      textStyle1.DEFAULT.toString();
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle_Builder3.setMaxWidth(272);
      textStyle_Builder0.setLeftPad(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder5.getIndent();
      textStyle_Builder6.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.LEFT;
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textStyle_Builder1.setLeftPad(0);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setMinWidth((-4207));
      textStyle_Builder2.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.setLeftPad((-4207));
      textStyle_Builder1.setMinWidth((-814));
      textStyle_Builder2.setLeftPad((-4207));
      textStyle_Builder2.setMaxWidth((-4207));
      textStyle_Builder0.isScalable();
      TextStyle.Alignment textStyle_Alignment1 = TextStyle.Alignment.RIGHT;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder0.setAlignment(textStyle_Alignment1);
      textStyle_Builder1.setMinWidth(0);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder3.setLeftPad(0);
      textStyle_Builder2.setMaxWidth((-2502));
      TextStyle.Alignment textStyle_Alignment2 = TextStyle.Alignment.LEFT;
      textStyle_Builder4.setAlignment(textStyle_Alignment2);
      TextStyle textStyle0 = textStyle_Builder0.get();
      textStyle0.toString();
      textStyle_Builder4.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setTextStyle(textStyle0);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setIndent(Integer.MAX_VALUE);
      TextStyle.builder();
      textStyle0.toString();
      textStyle0.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle0.DEFAULT.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setScalable(true);
      textStyle_Builder0.setScalable(true);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setMinWidth(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle_Builder2.setMaxWidth(2);
      TextStyle textStyle1 = textStyle_Builder1.get();
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle0.getLeftPad();
      textStyle0.getMaxWidth();
      textStyle0.getMinWidth();
      textStyle_Builder5.getIndent();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      textStyle0.DEFAULT.pad(false, charBuffer0);
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      textStyle_Builder1.getIndent();
      textStyle_Builder0.setMinWidth(0);
      textStyle_Builder0.isScalable();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.DEFAULT.toString();
      TextStyle.builder();
      textStyle0.getLeftPad();
      textStyle0.getIndent();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setLeftPad((-1748));
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setMinWidth(2269);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setIndent(2269);
      textStyle_Builder1.setMinWidth((-6017));
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder2.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textStyle0.pad(true, (CharSequence) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextStyle", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setScalable(false);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.LEFT;
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      TextStyle textStyle0 = textStyle_Builder0.get();
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setMaxWidth((-1090));
      TextStyle textStyle1 = TextStyle.DEFAULT;
      textStyle_Builder3.setIndent((-1090));
      textStyle1.toString();
      textStyle0.isScalable();
      textStyle_Builder0.getIndent();
      TextStyle.builder();
      textStyle_Builder3.setTextStyle(textStyle1);
      textStyle1.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.builder();
      TextStyle.builder();
      textStyle0.toString();
      textStyle0.DEFAULT.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle0.toString();
      textStyle0.getLeftPad();
      TextStyle.builder();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.isScalable();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMinWidth(1232);
      textStyle_Builder0.setMaxWidth((-5743));
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.getLeftPad();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.LEFT;
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setScalable(false);
      textStyle_Builder0.getMinWidth();
      textStyle_Builder0.getLeftPad();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.isScalable();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder0.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getMinWidth();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(1600);
      textStyle_Builder1.isScalable();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      textStyle0.getAlignment();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setIndent(0);
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(1255);
      textStyle_Builder1.get();
      textStyle_Builder1.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setMaxWidth(0);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMinWidth(0);
      textStyle_Builder0.isScalable();
      TextStyle textStyle1 = textStyle_Builder2.get();
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setLeftPad(0);
      TextStyle.Alignment.values();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder0.setTextStyle(textStyle0);
      textStyle_Builder0.setLeftPad(0);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder0.setScalable(false);
      textStyle_Builder1.setMaxWidth(272);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle_Builder3.getIndent();
      textStyle_Builder4.setTextStyle(textStyle0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.DEFAULT.toString();
      TextStyle.builder();
      textStyle0.DEFAULT.toString();
      textStyle0.DEFAULT.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle0.getAlignment();
      textStyle0.getMaxWidth();
      textStyle0.getIndent();
      int int0 = TextStyle.UNSET_MAX_WIDTH;
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder2.setMaxWidth(895);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder4 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Builder textStyle_Builder5 = textStyle_Builder4.setLeftPad(0);
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      textStyle_Builder1.setScalable(true);
      textStyle_Builder2.setIndent(0);
      textStyle_Builder3.setMaxWidth(0);
      textStyle0.toString();
      textStyle_Builder5.getIndent();
      textStyle1.getLeftPad();
      textStyle0.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.getIndent();
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(0);
      textStyle0.toString();
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMaxWidth(Integer.MAX_VALUE);
      textStyle0.toString();
      textStyle0.DEFAULT.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder0.setMinWidth(895);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder3.setIndent(Integer.MAX_VALUE);
      textStyle_Builder0.isScalable();
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.RIGHT;
      textStyle_Builder1.setAlignment(textStyle_Alignment0);
      TextStyle.Builder textStyle_Builder5 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder4.get();
      textStyle_Builder5.setLeftPad(Integer.MAX_VALUE);
      TextStyle.Alignment.values();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      textStyle_Builder1.setScalable(true);
      textStyle_Builder2.setIndent(0);
      textStyle_Builder4.setLeftPad(Integer.MAX_VALUE);
      textStyle1.getMinWidth();
      TextStyle.Alignment.values();
      textStyle1.toString();
      textStyle1.getLeftPad();
      textStyle0.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      textStyle0.DEFAULT.toString();
      textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.isScalable();
      TextStyle.Builder textStyle_Builder3 = TextStyle.builder();
      textStyle_Builder1.setMaxWidth(895);
      TextStyle textStyle1 = textStyle_Builder2.get();
      textStyle_Builder3.setLeftPad(Integer.MAX_VALUE);
      textStyle_Builder2.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      TextStyle.builder();
      textStyle_Builder1.setScalable(true);
      textStyle_Builder1.setIndent(895);
      textStyle_Builder2.setMaxWidth((-1));
      textStyle_Builder2.setMaxWidth(Integer.MAX_VALUE);
      textStyle1.toString();
      textStyle1.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle0.DEFAULT.toString();
      TextStyle.Builder textStyle_Builder1 = textStyle_Builder0.setIndent(895);
      TextStyle.Builder textStyle_Builder2 = textStyle_Builder0.setMinWidth(895);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      TextStyle.Builder textStyle_Builder3 = textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textStyle_Builder2.isScalable();
      textStyle_Builder1.setIndent(895);
      TextStyle textStyle1 = textStyle_Builder3.get();
      TextStyle.Alignment.values();
      textStyle_Builder3.getMaxWidth();
      textStyle1.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder1.setLeftPad(895);
      TextStyle.Builder textStyle_Builder4 = textStyle_Builder0.setScalable(true);
      textStyle_Builder1.setIndent(0);
      textStyle_Builder3.setMaxWidth((-1));
      textStyle1.pad(false, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textStyle_Builder4.setScalable(true);
      textStyle_Builder0.setLeftPad(Integer.MAX_VALUE);
      textStyle1.getMinWidth();
      textStyle1.toString();
      textStyle_Builder2.getIndent();
      textStyle1.toString();
      assertEquals(895, textStyle_Builder0.getMinWidth());
      
      textStyle_Builder4.setTextStyle(textStyle0);
      textStyle0.toString();
      textStyle0.toString();
      String string0 = textStyle0.toString();
      assertEquals("TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = textStyle_Builder0.get();
      boolean boolean0 = textStyle0.isScalable();
      assertTrue(boolean0);
      
      int int0 = textStyle_Builder0.getIndent();
      assertEquals(0, int0);
      
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      assertEquals(Integer.MAX_VALUE, textStyle_Builder1.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      int int0 = textStyle_Builder0.getLeftPad();
      assertTrue(textStyle_Builder0.isScalable());
      assertEquals(0, int0);
      assertEquals(Integer.MAX_VALUE, textStyle_Builder0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      TextStyle.builder();
      textStyle_Builder0.setLeftPad(0);
      TextStyle.builder();
      int int0 = textStyle_Builder0.getMinWidth();
      assertEquals(0, textStyle_Builder0.getLeftPad());
      assertEquals(0, int0);
      
      int int1 = textStyle_Builder1.getMaxWidth();
      assertEquals(Integer.MAX_VALUE, int1);
      
      TextStyle.Builder textStyle_Builder2 = TextStyle.builder();
      assertTrue(textStyle_Builder2.isScalable());
  }
}
