/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:41:34 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.apache.commons.cli.help.Util;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Util_ESTest extends Util_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = Util.repeatSpace(3735);
      String string1 = Util.ltrim(string0);
      Util.isWhitespace('p');
      Util.isWhitespace('+');
      Util.indexOfNonWhitespace("", (-2007));
      Util.indexOfNonWhitespace("", 0);
      Util.isWhitespace('^');
      String string2 = Util.defaultValue((String) null, string0);
      assertFalse(string2.equals((Object)string1));
      
      char[] charArray0 = new char[7];
      charArray0[0] = 'X';
      charArray0[2] = '^';
      charArray0[3] = '+';
      charArray0[4] = '^';
      charArray0[5] = '^';
      charArray0[6] = '^';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      Util.defaultValue(charBuffer0, charBuffer0);
      Util.defaultValue((CharBuffer) null, (CharBuffer) null);
      Util.isEmpty((CharSequence) null);
      Util.ltrim(string0);
      // Undeclared exception!
      Util.rtrim(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = Util.repeatSpace(1010);
      Util.indexOfNonWhitespace(string0, 1010);
      String string1 = Util.defaultValue(string0, (String) null);
      Util.rtrim(string1);
      Util.indexOfNonWhitespace("", 32);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Util.isWhitespace('Y');
      Util.rtrim("]d]0");
      Util.indexOfNonWhitespace("]d]0", 0);
      Util.ltrim("]d]0");
      Util.indexOfNonWhitespace("]d]0", 1);
      Util.isWhitespace('Y');
      Util.indexOfNonWhitespace("]d]0", 0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Util.repeatSpace(0);
      Util.ltrim("");
      Util.repeatSpace(0);
      Util.repeat(32, '(');
      Util.repeatSpace(414);
      Util.indexOfNonWhitespace("", 0);
      Util.isEmpty("");
      // Undeclared exception!
      try { 
        Util.indexOfNonWhitespace("                                                                                                                                                                                                                                                                                                                                                                                                                              ", (-1));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(321);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 32);
      Util.indexOfNonWhitespace(charBuffer1, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Util.rtrim((String) null);
      Util.ltrim("");
      Util.repeat(1, 'a');
      Util.indexOfNonWhitespace((CharSequence) null, 2595);
      Util.isWhitespace('a');
      Util.isEmpty("");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Util.repeatSpace(0);
      Util.defaultValue((CharSequence) "", (CharSequence) "");
      Util.isEmpty("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Util.ltrim("");
      Util.repeat(0, '-');
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Util.ltrim("org.apache.commons.cli.help.Util");
      Util.indexOfNonWhitespace("org.apache.commons.cli.help.Util", 4608);
      Util.defaultValue("org.apache.commons.cli.help.Util", "");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Util.defaultValue((CharSequence) null, (CharSequence) null);
      Util.indexOfNonWhitespace((CharSequence) null, 0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Util.rtrim("w:%]MPqM1y:qD8");
      Util.isWhitespace('>');
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Util.defaultValue("omn'5gb%!_` ", "");
      Util.repeatSpace(14);
      Util.ltrim("              ");
      Util.indexOfNonWhitespace("", 14);
      Util.defaultValue("", "omn'5gb%!_` ");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        Util.repeatSpace((-1385));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Util.defaultValue("org.apache.commons.cli.help.Util", "y[fw_[@oZV9");
      char char0 = '$';
      Util.repeat(3838, '$');
      Util.defaultValue("org.apache.commons.cli.help.Util", (String) null);
      Util.defaultValue("{>3=?-GWe", (String) null);
      Util.rtrim("!b|)6<;\"6E");
      Util.rtrim("org.apache.commons.cli.help.Util");
      int int0 = 0;
      Util.indexOfNonWhitespace((CharSequence) null, 0);
      Util.rtrim("org.apache.commons.cli.help.Util");
      String string0 = "";
      Util.ltrim("");
      // Undeclared exception!
      try { 
        Util.repeat((-288), '$');
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Util.ltrim("");
      Util.ltrim((String) null);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Util.defaultValue("", "");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Util.rtrim("N");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Util.rtrim("");
      Util.ltrim("");
      String string0 = Util.repeatSpace(1);
      assertEquals(" ", string0);
      
      Util.defaultValue("", "");
      Util.indexOfNonWhitespace("", 1);
      Util.indexOfNonWhitespace("", 1);
      Util.defaultValue((CharBuffer) null, (CharBuffer) null);
      String string1 = Util.ltrim(" ");
      String string2 = Util.rtrim(" ");
      assertTrue(string2.equals((Object)string1));
      assertEquals("", string2);
      
      int int0 = Util.indexOfNonWhitespace("", 1);
      assertEquals((-1), int0);
      
      String string3 = Util.repeat(0, '<');
      assertEquals("", string3);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Util.repeatSpace(1);
      Util.ltrim(" ");
      Util.isWhitespace('l');
      Util.isWhitespace('&');
      Util.repeatSpace(1);
      Util.repeatSpace(1);
      Util.isEmpty(" ");
      Util.repeat(1, '$');
      Util.ltrim("$");
      Util.ltrim("+<1Ab");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Util.rtrim("$7^<NH<v3&V)Nst");
      Util.defaultValue("$7^<NH<v3&V)Nst", "$7^<NH<v3&V)Nst");
      Util.defaultValue("$7^<NH<v3&V)Nst", "b'uLA/)Mq\"eG;Nw%W");
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Util.defaultValue((CharBuffer) null, (CharBuffer) null);
      Util.ltrim((String) null);
      Util.ltrim((String) null);
      Util.repeat(1251, 'l');
      Util.rtrim("");
      Util.isWhitespace('\u0010');
      String string0 = Util.repeat(2608, '2');
      Util.isEmpty(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Util.isWhitespace('B');
      Util.repeatSpace(3828);
      boolean boolean0 = Util.isWhitespace('B');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = Util.rtrim("org.apache.commons.cli.help.Util");
      assertEquals("org.apache.commons.cli.help.Util", string0);
  }
}
