/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:47:23 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.GnuParser;
import org.apache.commons.cli.Options;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GnuParser_ESTest extends GnuParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[8];
      stringArray0[1] = "-=;@Tf";
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, false);
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray0 = new String[6];
      stringArray0[5] = "-2SQvEc7N22W'i";
      // Undeclared exception!
      try { 
        gnuParser0.flatten((Options) null, stringArray0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.GnuParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "-=;@Tf";
      options0.addRequiredOption("a", "", true, "-- [o4<+#y");
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      String[] stringArray2 = gnuParser0.flatten(options0, stringArray1, true);
      assertEquals(2, stringArray2.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[8];
      stringArray0[3] = "-- [o4<+#y";
      options0.addRequiredOption("a", "", true, "-- [o4<+#y");
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      String[] stringArray2 = gnuParser0.flatten(options0, stringArray1, true);
      assertEquals(2, stringArray2.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[8];
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      assertEquals(0, stringArray1.length);
  }
}
