/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:30:11 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since((String) null);
      option_Builder0.required(true);
      option_Builder0.optionalArg(true);
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgs((-769));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.setArgName(" for removal");
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      int int0 = Option.UNINITIALIZED;
      option0.getArgName();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Option option0 = new Option("@", "@");
      option0.getValue("@");
      Option.builder();
      option0.clearValues();
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.clearValues();
      option0.setDescription("@");
      option0.setArgs(593);
      Option option1 = (Option)option0.clone();
      Option.builder("@");
      option0.hashCode();
      option0.hashCode();
      option0.setDescription("@");
      option0.getConverter();
      option0.getValueSeparator();
      option0.setLongOpt("");
      option0.isValuesEmpty();
      option0.setOptionalArg(true);
      option0.requiresArg();
      option0.getValueSeparator();
      option0.hasOptionalArg();
      option0.getArgName();
      option0.hasArgName();
      Option option2 = new Option((String) null, false, "@");
      option0.getArgName();
      Option.builder();
      option0.getType();
      option0.isValuesEmpty();
      option0.processValue("@");
      option0.acceptsArg();
      Option.builder();
      option0.getValue("7h={p(al");
      Option option3 = (Option)option1.clone();
      option2.equals(option3);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(true);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option0.setRequired(true);
      option0.setDescription("value");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option0.getDescription();
      option0.hasArgs();
      Option.builder();
      option_Builder6.hasArg(true);
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.toDeprecatedString();
      option0.isDeprecated();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.required();
      Option.builder();
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgName("--");
      option0.setArgs((-2));
      option0.processValue("--");
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.toString();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      option0.getValuesList();
      // Undeclared exception!
      try { 
        option0.processValue(":3X]h");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Option option0 = new Option("@", "@");
      option0.getValue("@");
      option0.clone();
      Option.builder();
      option0.toString();
      option0.clearValues();
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.clearValues();
      option0.setDescription("");
      option0.setArgs(593);
      option0.clone();
      Option.builder("@");
      option0.hashCode();
      option0.hashCode();
      option0.setDescription("@");
      option0.getConverter();
      option0.getValueSeparator();
      option0.isValuesEmpty();
      option0.setOptionalArg(true);
      option0.requiresArg();
      option0.getValueSeparator();
      option0.hasOptionalArg();
      option0.getArgName();
      option0.hasArgName();
      option0.clone();
      Option.builder("@");
      Option.builder();
      option0.getType();
      option0.isValuesEmpty();
      option0.processValue("[ Option @ :: @ :: class java.lang.String ]");
      option0.acceptsArg();
      Option.builder();
      option0.getValue("7h={p(al");
      option0.getOpt();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder2 = option_Builder1.required();
      option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder3 = option_Builder2.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder3.get();
      String string0 = "value";
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option0.processValue("Empty option name.");
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder2.deprecated(deprecatedAttributes0);
      try { 
        option0.getValue(279);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 279, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Object object0 = option0.clone();
      Class<Integer> class0 = Integer.class;
      option0.equals(object0);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.isDeprecated();
      option0.toString();
      option0.setType(class0);
      option0.hasOptionalArg();
      option0.setValueSeparator('(');
      option0.hasArgName();
      option0.acceptsArg();
      option0.isValuesEmpty();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.builder();
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option_Builder0.argName("|A3W+lhFiM3U");
      option0.equals(option_Builder0);
      option0.setArgs((-2));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.setType((Object) null);
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.hasArg();
      Option.builder();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Option option0 = new Option("@", "@");
      option0.getValue("@");
      option0.clone();
      Option.builder();
      option0.toString();
      option0.clearValues();
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.clearValues();
      option0.setDescription("");
      option0.setArgs(593);
      option0.clone();
      Option.builder("@");
      option0.hashCode();
      option0.hashCode();
      option0.setDescription("@");
      option0.getConverter();
      option0.getValueSeparator();
      option0.setLongOpt("");
      option0.isValuesEmpty();
      option0.setOptionalArg(true);
      option0.requiresArg();
      option0.getValueSeparator();
      option0.hasOptionalArg();
      option0.getArgName();
      option0.hasArgName();
      option0.clone();
      option0.getArgName();
      Option.builder();
      option0.getType();
      option0.isValuesEmpty();
      option0.processValue("[ Option @ :: @ :: class java.lang.String ]");
      option0.acceptsArg();
      Option.builder();
      option0.getValue("7h={p(al");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      option0.setValueSeparator('h');
      // Undeclared exception!
      try { 
        option0.processValue(":3X]h");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      Class<Object> class0 = Object.class;
      Option.Builder option_Builder2 = option_Builder1.type(class0);
      Option.Builder option_Builder3 = option_Builder2.desc("4TTu:^");
      Option.Builder option_Builder4 = option_Builder3.longOpt("4TTu:^");
      Option option0 = option_Builder4.get();
      option0.setArgName("4TTu:^");
      option0.hasValueSeparator();
      option0.hasArgName();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(false);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option_Builder6.argName("org.apache.commons.cli.TypeHandler");
      option0.getDescription();
      option0.hasArgs();
      Option.builder();
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.toDeprecatedString();
      option0.getId();
      option0.toString();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      Class<Object> class0 = Object.class;
      option0.setType(class0);
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      option0.getValues();
      option0.setValueSeparator('h');
      option0.setArgs(17);
      option0.processValue(":3X]h");
      option0.toDeprecatedString();
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.clearValues();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.getValues();
      option0.setRequired(true);
      // Undeclared exception!
      try { 
        option0.processValue(":3X]h");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.builder();
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgs((-2));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.getValues();
      option0.setRequired(true);
      option0.toString();
      option0.setRequired(true);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.setRequired(true);
      Class<String> class0 = String.class;
      option0.setType(class0);
      option0.setValueSeparator('c');
      option0.getSince();
      option0.toDeprecatedString();
      option0.toDeprecatedString();
      Option.builder((String) null);
      option0.getValue((-119));
      option0.getOpt();
      option0.toDeprecatedString();
      option0.getValue((-119));
      option0.getValueSeparator();
      option0.setType((Object) null);
      option0.toString();
      option0.getValues();
      option0.hasArg();
      option0.hasLongOpt();
      option0.getType();
      option0.getConverter();
      option0.isDeprecated();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Option option1 = (Option)option0.clone();
      option1.getConverter();
      option0.equals(option1);
      Option.builder((String) null);
      option0.getDescription();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.isDeprecated();
      option0.toString();
      option0.hasOptionalArg();
      option0.hasArgName();
      option0.acceptsArg();
      option0.isValuesEmpty();
      option0.hasArg();
      Option option2 = (Option)option0.clone();
      option0.getKey();
      option0.getValueSeparator();
      option0.toString();
      option0.getValue(3616);
      Option.builder();
      // Undeclared exception!
      try { 
        option2.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.getValues();
      option0.setRequired(true);
      option0.toString();
      option0.setRequired(true);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.setRequired(true);
      Class<String> class0 = String.class;
      option0.setType(class0);
      option0.setValueSeparator('c');
      option0.processValue("Option ");
      option0.getSince();
      option0.toDeprecatedString();
      option0.toDeprecatedString();
      Option.builder((String) null);
      int int0 = (-119);
      try { 
        option0.getValue((-119));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Option option1 = (Option)option0.clone();
      Class<Integer> class0 = Integer.class;
      option0.equals(option1);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.toString();
      option0.equals("Sr@=");
      option0.hasOptionalArg();
      option0.hasArgName();
      option0.acceptsArg();
      // Undeclared exception!
      try { 
        option0.addValue("org.apache.commons.cli.Option$1");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(false);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option_Builder5.longOpt("Empty option name.");
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option0.getDescription();
      option0.hasArgs();
      option_Builder6.hasArg(true);
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(false);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option_Builder5.longOpt("Empty option name.");
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option0.getDescription();
      option0.hasArgs();
      option_Builder6.hasArg(true);
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.getDeprecated();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Option option0 = new Option((String) null, true, "`~fqVB.RU9?A'xjOT7");
      option0.hashCode();
      option0.setDescription("org.apache.commons.cli.Util");
      option0.getDeprecated();
      option0.processValue("IJ");
      option0.isValuesEmpty();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Option option0 = new Option((String) null, "oa 2hA M.");
      option0.setArgName("--");
      option0.getSince();
      option0.hasArg();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since((String) null);
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      Converter<?, ?> converter0 = option0.getConverter();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      option0.setConverter(converter0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Class<Integer> class0 = Integer.class;
      option0.equals(option0);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.getValues();
      option0.equals((Object) null);
      option0.isDeprecated();
      option0.toString();
      option0.hasOptionalArg();
      option0.hasArgName();
      option0.acceptsArg();
      option0.isValuesEmpty();
      // Undeclared exception!
      try { 
        option0.addValue("org.apache.commons.cli.Option$1");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.setRequired(true);
      option0.setValueSeparator('h');
      option0.setArgs(17);
      option0.processValue(":3X]h");
      option0.toDeprecatedString();
      option0.toDeprecatedString();
      option0.setArgs((-43));
      option0.setArgName((String) null);
      option0.setDescription("LS-#B#'+}m9");
      option0.toString();
      option0.clone();
      option0.setRequired(false);
      option0.getValue();
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.setRequired(true);
      option0.setArgs((-2));
      option0.processValue(":3X]h");
      option0.toDeprecatedString();
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Option option0 = new Option("?0", true, "?0");
      option0.getKey();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since((String) null);
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgs((-769));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.setRequired(true);
      option0.setValueSeparator('h');
      option0.setArgs(17);
      option0.processValue(":3X]h");
      option0.toDeprecatedString();
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Option option0 = new Option("d", "d");
      Option.builder();
      option0.toString();
      option0.clearValues();
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.clearValues();
      option0.setDescription("");
      option0.setArgs(600);
      Option option1 = (Option)option0.clone();
      Option.builder("d");
      option0.hashCode();
      option0.hashCode();
      option0.setDescription("d");
      option0.toString();
      option0.getConverter();
      option0.getValueSeparator();
      option0.setLongOpt("");
      option0.isValuesEmpty();
      option0.setOptionalArg(true);
      option0.requiresArg();
      option0.getValueSeparator();
      option0.hasOptionalArg();
      option0.getArgName();
      option0.hasArgName();
      option0.getConverter();
      option0.clone();
      option0.getArgName();
      Option.builder();
      option0.getType();
      option0.isValuesEmpty();
      option0.processValue("[ Option d :: d :: class java.lang.String ]");
      option0.acceptsArg();
      Option.builder();
      option1.getValue((-1));
      option0.hasLongOpt();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      Class<Option> class0 = Option.class;
      option0.setType(class0);
      option0.setRequired(true);
      option0.getType();
      option0.setArgs((-1304));
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, false, (String) null);
      option0.setValueSeparator('F');
      option0.setRequired(false);
      Option option1 = new Option((String) null, false, (String) null);
      option0.getValue((String) null);
      option1.setValueSeparator('#');
      boolean boolean0 = false;
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Option option0 = new Option((String) null, false, "G_bTQJ^arzp!i");
      option0.setDescription("Mj_");
      option0.hasArgs();
      option0.clone();
      option0.clone();
      option0.equals("uZ;#;g{#np,vFO(#");
      Object object0 = option0.getType();
      option0.toDeprecatedString();
      Class<Object> class0 = Object.class;
      option0.setType(class0);
      option0.setArgs(9);
      Option.builder();
      option0.hashCode();
      option0.equals(object0);
      option0.getOpt();
      option0.toString();
      option0.clone();
      option0.getValuesList();
      option0.getType();
      option0.hasArgs();
      option0.getSince();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Option option1 = (Option)option0.clone();
      option1.setLongOpt((String) null);
      Class<Integer> class0 = Integer.class;
      option0.equals(option1);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.hasArgName();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.isDeprecated();
      option0.toString();
      option0.hasOptionalArg();
      option0.getValue();
      option0.hasArgName();
      option0.setDescription("");
      option1.getOpt();
      option0.getLongOpt();
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since((String) null);
      option_Builder0.required(true);
      option_Builder0.valueSeparator('+');
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      option0.hasArg();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Option option0 = new Option((String) null, false, "value");
      option0.hasArgName();
      option0.setRequired(true);
      Option.builder();
      option0.getSince();
      option0.getValue("value");
      option0.isDeprecated();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder0.hasArg();
      option_Builder1.optionalArg(true);
      option_Builder0.argName((String) null);
      option_Builder1.valueSeparator();
      option_Builder0.since((String) null);
      Option option0 = new Option((String) null, false, "^Z#Ls{(");
      Option option1 = (Option)option0.clone();
      option1.getConverter();
      option0.getValues();
      option0.getValue(1585);
      option_Builder1.required();
      option0.getDeprecated();
      option0.toString();
      option1.getArgs();
      // Undeclared exception!
      try { 
        option0.addValue("^Z#Ls{(");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Option option1 = new Option((String) null, (String) null);
      Class<Integer> class0 = Integer.class;
      option0.equals(option1);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.hasArgName();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.isDeprecated();
      option0.toString();
      option0.hasOptionalArg();
      option0.getValue();
      option0.hasArgName();
      option0.setDescription("");
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setRequired(true);
      option0.setArgs(0);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      Option.builder((String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.setRequired(true);
      option0.setArgs(0);
      option0.acceptsArg();
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      Object object0 = option0.clone();
      Class<Integer> class0 = Integer.class;
      option0.equals(object0);
      option0.setType(class0);
      Option.builder((String) null);
      option0.getDescription();
      option0.hasArgName();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.isDeprecated();
      option0.toString();
      option0.hasOptionalArg();
      option0.getValue();
      option0.hasArgName();
      option0.setDescription("");
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Option option0 = new Option((String) null, false, "(l:[`[,,qU[");
      option0.getLongOpt();
      Option.builder();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Option option0 = new Option("zCcsluw-x", "zCcsluw-x", false, "zCcsluw-x");
      option0.setArgs((-769));
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setValueSeparator('s');
      option0.hasArgs();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.converter(converter0);
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      Option.Builder option_Builder2 = option_Builder1.argName("zCcsluw-x");
      Option.Builder option_Builder3 = option_Builder2.required(false);
      Option.Builder option_Builder4 = option_Builder3.required();
      option_Builder4.required();
      Option.Builder option_Builder5 = option_Builder0.valueSeparator('R');
      option_Builder3.optionalArg(false);
      Option.Builder option_Builder6 = option_Builder4.option("zCcsluw-x");
      option_Builder6.hasArg();
      option0.setRequired(false);
      option0.hasValueSeparator();
      option0.setLongOpt("$");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder3.deprecated(deprecatedAttributes0);
      option_Builder5.hasArg(false);
      option0.getLongOpt();
      option0.setValueSeparator('l');
      option0.hasArgs();
      option0.getLongOpt();
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      option0.toString();
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      DeprecatedAttributes.builder();
      option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      Option.Builder option_Builder3 = option_Builder2.longOpt("[ Option null  [ARG] :: null :: class java.lang.String ]");
      option_Builder1.valueSeparator();
      Option.Builder option_Builder4 = option_Builder3.hasArg(true);
      option_Builder1.since("!JHj");
      option_Builder2.deprecated();
      option_Builder2.argName((String) null);
      deprecatedAttributes0.toString();
      option_Builder0.required();
      option0.clone();
      Option.Builder option_Builder5 = option_Builder4.numberOfArgs(544);
      option_Builder2.deprecated(deprecatedAttributes0);
      option_Builder4.hasArgs();
      option_Builder5.optionalArg(true);
      option_Builder5.hasArg();
      option_Builder5.valueSeparator();
      option0.equals((Object) null);
      option0.setArgName((String) null);
      option0.clone();
      option0.toDeprecatedString();
      option0.hasValueSeparator();
      // Undeclared exception!
      try { 
        option0.addValue("");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.setRequired(true);
      option0.setArgs(0);
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Option option0 = new Option("@Lf", "@Lf", false, "N:2U ");
      option0.hashCode();
      option0.toDeprecatedString();
      option0.setLongOpt("@Lf");
      option0.getConverter();
      option0.getConverter();
      option0.isRequired();
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("converterMap");
      Option.Builder option_Builder2 = option_Builder1.valueSeparator('!');
      Option.Builder option_Builder3 = option_Builder2.desc((String) null);
      Option.Builder option_Builder4 = option_Builder3.required(false);
      Option option0 = option_Builder1.get();
      option_Builder3.argName((String) null);
      Option.Builder option_Builder5 = option_Builder4.since((String) null);
      option_Builder5.numberOfArgs(32);
      option_Builder1.numberOfArgs(32);
      option_Builder5.hasArgs();
      Option.Builder option_Builder6 = option_Builder5.required(false);
      option_Builder6.hasArg(false);
      Option option1 = new Option((String) null, "7 c0B0vdJX", false, "");
      option1.toString();
      option1.setArgName("org.apache.commons.cli.Option");
      option0.equals(option_Builder5);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.longOpt((String) null);
      Option.Builder option_Builder2 = option_Builder1.option((String) null);
      Option.Builder option_Builder3 = option_Builder2.valueSeparator('i');
      Option.Builder option_Builder4 = option_Builder3.hasArg(true);
      // Undeclared exception!
      try { 
        option_Builder4.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Option option0 = new Option((String) null, false, "Either opt or longOpt must be specified");
      option0.getConverter();
      option0.toString();
      option0.toString();
      option0.clearValues();
      option0.toDeprecatedString();
      option0.getArgName();
      option0.setRequired(true);
      option0.toString();
      option0.isRequired();
      option0.hasArgName();
      Option.Builder option_Builder0 = Option.builder((String) null);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder2 = option_Builder1.hasArg(false);
      Option.Builder option_Builder3 = option_Builder2.deprecated();
      Option.Builder option_Builder4 = option_Builder3.desc("J#fch<'lHs*_iOSN+");
      Option.Builder option_Builder5 = option_Builder4.valueSeparator('u');
      option_Builder5.longOpt("J#fch<'lHs*_iOSN+");
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgName((String) null);
      option0.clone();
      option0.getValue();
      option0.toDeprecatedString();
      option0.setArgName((String) null);
      option0.getOpt();
      option0.setDescription("");
      Option.Builder option_Builder0 = Option.builder();
      option0.setLongOpt("97U^o=w'x7p>r");
      option0.getValue(61);
      Class<String> class0 = String.class;
      option_Builder0.type(class0);
      option0.setValueSeparator('K');
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder0.hasArg();
      option_Builder1.optionalArg(true);
      option_Builder0.argName((String) null);
      option_Builder1.valueSeparator();
      option_Builder0.since((String) null);
      Option option0 = new Option((String) null, false, "^Z#Ls{(");
      option0.clone();
      option0.getValues();
      option0.getValue(1585);
      option_Builder1.required();
      option0.getDeprecated();
      option0.toString();
      // Undeclared exception!
      try { 
        option0.addValue("^Z#Ls{(");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Option option0 = new Option("@s0", "=_IS'rOB<;qj!bHP", true, "=_IS'rOB<;qj!bHP");
      option0.setOptionalArg(true);
      option0.getConverter();
      option0.getDeprecated();
      option0.getValueSeparator();
      // Undeclared exception!
      try { 
        Option.builder(" for removal");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Option option0 = new Option("Q3", "Q3", false, "_f$m$.IaI4|n5");
      String string0 = "22?C&4";
      Object object0 = new Object();
      option0.equals(object0);
      Class<Object> class0 = Object.class;
      option0.setType(class0);
      // Undeclared exception!
      try { 
        option0.processValue(" for removal");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('M');
      option_Builder0.hasArgs();
      String string0 = "\\u";
      Option.Builder option_Builder2 = option_Builder1.longOpt(string0);
      Option.Builder option_Builder3 = option_Builder2.since(string0);
      Option.Builder option_Builder4 = option_Builder3.hasArgs();
      option_Builder4.hasArg(false);
      option_Builder2.hasArgs();
      Option option0 = option_Builder4.get();
      String string1 = "";
      // Undeclared exception!
      try { 
        option0.addValue("");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Option option0 = new Option((String) null, false, "Empty option name.");
      String string0 = "converterMap";
      option0.setLongOpt((String) null);
      option0.setValueSeparator('B');
      // Undeclared exception!
      try { 
        option0.addValue("converterMap");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      Class<String> class0 = String.class;
      Option.Builder option_Builder2 = option_Builder1.type(class0);
      option_Builder1.hasArgs();
      String string0 = "~?\\W6u:X*zB4n=";
      option_Builder2.optionalArg(true);
      Option.Builder option_Builder3 = option_Builder2.since("~?W6u:X*zB4n=");
      Option.Builder option_Builder4 = option_Builder3.hasArg(true);
      option_Builder4.required();
      option_Builder4.required(true);
      // Undeclared exception!
      try { 
        option_Builder4.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      boolean boolean0 = true;
      Option option0 = new Option((String) null, true, (String) null);
      option0.toString();
      String string0 = "";
      option0.processValue("");
      Class<String> class0 = String.class;
      option0.setType(class0);
      option0.clearValues();
      Option.Builder option_Builder0 = Option.builder();
      option0.getKey();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.setArgs(0);
      option0.clearValues();
      option0.isValuesEmpty();
      option0.hasArgName();
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.argName("P-a");
      Option.Builder option_Builder2 = option_Builder1.required(true);
      Option.Builder option_Builder3 = option_Builder2.hasArgs();
      try { 
        option_Builder3.option("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Option option0 = new Option("Xn", false, "Xn");
      option0.isValuesEmpty();
      option0.clearValues();
      option0.getValues();
      option0.toString();
      option0.toDeprecatedString();
      option0.setValueSeparator('4');
      option0.getConverter();
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      deprecatedAttributes0.toString();
      Option option0 = new Option("value", "org.apache.commons.cli.Option$Builder", true, " [ARG]");
      option0.getDeprecated();
      option0.setRequired(true);
      option0.getArgs();
      option0.requiresArg();
      option0.processValue(" [ARG]");
      Option.builder("Deprecated");
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Option option0 = new Option("oz", true, (String) null);
      option0.setLongOpt((String) null);
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("oz");
      Option.Builder option_Builder2 = option_Builder1.required(false);
      option_Builder2.hasArgs();
      Option.Builder option_Builder3 = option_Builder2.since("Either opt or longOpt must be specified");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue((-2));
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("y");
      Option.Builder option_Builder1 = option_Builder0.required();
      Option.Builder option_Builder2 = option_Builder1.hasArg(false);
      Option.Builder option_Builder3 = option_Builder2.optionalArg(true);
      Option.Builder option_Builder4 = option_Builder3.numberOfArgs(0);
      option_Builder3.hasArg();
      option_Builder4.required(false);
      option_Builder1.numberOfArgs(0);
      Option option0 = option_Builder4.get();
      option0.getValue(0);
      Class<String> class0 = String.class;
      Option.Builder option_Builder5 = option_Builder0.type(class0);
      option0.setRequired(true);
      option0.setArgName((String) null);
      option_Builder5.desc("P)8G],`>3CgU");
      option0.getValue("");
      option_Builder5.get();
      option0.getId();
      option_Builder5.longOpt("");
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      option_Builder0.optionalArg(true);
      option_Builder0.required(false);
      option_Builder0.optionalArg(false);
      Option option0 = new Option((String) null, false, (String) null);
      Object object0 = option0.clone();
      // Undeclared exception!
      try { 
        option0.setType(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.commons.cli.Option cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArg();
      option_Builder0.optionalArg(false);
      Option option0 = null;
      try {
        option0 = new Option("<}M,k<tRUcl", "<}M,k<tRUcl", true, "<}M,k<tRUcl");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '<'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "");
      option0.isDeprecated();
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option.Builder option_Builder1 = option_Builder0.required();
      Option.Builder option_Builder2 = option_Builder1.deprecated();
      Option.Builder option_Builder3 = option_Builder2.valueSeparator();
      Option.Builder option_Builder4 = option_Builder3.numberOfArgs(0);
      Option.Builder option_Builder5 = option_Builder4.hasArgs();
      option_Builder5.hasArg();
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Class<Object> class0 = Object.class;
      option_Builder0.type(class0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      option0.isValuesEmpty();
      option0.hasArgs();
      option0.hasArgs();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required(false);
      option_Builder1.required();
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.since("");
      Option.Builder option_Builder2 = option_Builder1.desc("`L<su");
      Option.Builder option_Builder3 = option_Builder2.hasArg(false);
      Option.Builder option_Builder4 = option_Builder3.deprecated((DeprecatedAttributes) null);
      // Undeclared exception!
      try { 
        option_Builder4.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required();
      Option.Builder option_Builder2 = option_Builder1.hasArg();
      Option.Builder option_Builder3 = option_Builder2.hasArg(true);
      Option.Builder option_Builder4 = option_Builder3.longOpt("flC-urA`");
      Option option0 = option_Builder4.get();
      option0.getValuesList();
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      String string0 = "\\u";
      option_Builder0.valueSeparator();
      Option.Builder option_Builder1 = option_Builder0.longOpt(string0);
      Option.Builder option_Builder2 = option_Builder1.hasArg();
      Option option0 = option_Builder2.get();
      option0.hashCode();
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      Option.Builder option_Builder2 = option_Builder1.valueSeparator();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder3 = option_Builder2.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder4 = option_Builder3.desc("");
      // Undeclared exception!
      try { 
        option_Builder4.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      String string0 = "";
      // Undeclared exception!
      try { 
        Option.builder("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      String string0 = "1K!Xv%4o#;v";
      Option option0 = null;
      try {
        option0 = new Option("", false, "1K!Xv%4o#;v");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      String string0 = ": ";
      Option option0 = null;
      try {
        option0 = new Option("org.apache.commons.cli.OptionValidator", ": ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.OptionValidator' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      String string0 = "M[*iOP{kp%5$\"*}\\7|";
      String string1 = "EEE MMM dd HH:mm:ss zzz yyyy";
      Option option0 = null;
      try {
        option0 = new Option("M[*iOP{kp%5$\"*}\u0007|", "M[*iOP{kp%5$\"*}\u0007|", true, "EEE MMM dd HH:mm:ss zzz yyyy");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'M[*iOP{kp%5$\"*}\u0007|' contains an illegal character : '['.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      String string0 = "Cannot add value, list full.";
      Option option0 = null;
      try {
        option0 = new Option("Cannot add value, list full.", "Cannot add value, list full.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'Cannot add value, list full.' contains an illegal character : ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.getConverter();
      option0.equals(option0);
      Option.builder((String) null);
      option0.setOptionalArg(true);
      option0.getDescription();
      option0.getValues();
      option0.equals((Object) null);
      option0.getValue();
      option0.toString();
      option0.hasOptionalArg();
      option0.hasArgName();
      option0.acceptsArg();
      option0.isValuesEmpty();
      option0.hasArg();
      Option option1 = (Option)option0.clone();
      option0.getKey();
      option0.getValueSeparator();
      option0.getValue(3616);
      Option.builder();
      // Undeclared exception!
      try { 
        option1.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Option option0 = new Option("aw", "aw");
      option0.clearValues();
      Converter<?, ?> converter0 = option0.getConverter();
      option0.getValue((-1423));
      option0.getValues();
      option0.setConverter(converter0);
      option0.equals(converter0);
      // Undeclared exception!
      try { 
        option0.addValue("aw");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Option option0 = new Option("@Lf", "@Lf", false, "N:2U ");
      option0.hashCode();
      option0.toDeprecatedString();
      option0.setLongOpt("@Lf");
      option0.getConverter();
      option0.isRequired();
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      String string0 = " s#nce5";
      Option option0 = null;
      try {
        option0 = new Option(" s#nce5", " s#nce5");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "v~WZGwyT");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      // Undeclared exception!
      try { 
        option0.processValue(":3X]h");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Option option0 = new Option("zCcsluw-x", "zCcsluw-x", false, "zCcsluw-x");
      option0.setArgs((-1));
      Converter<?, ?> converter0 = option0.getConverter();
      option0.hasArgs();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.converter(converter0);
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      Option.Builder option_Builder2 = option_Builder1.argName("zCcsluw-x");
      Option.Builder option_Builder3 = option_Builder2.required(false);
      Option.Builder option_Builder4 = option_Builder3.required();
      option_Builder4.required();
      Option.Builder option_Builder5 = option_Builder0.valueSeparator('R');
      option_Builder3.optionalArg(false);
      Option.Builder option_Builder6 = option_Builder4.option("zCcsluw-x");
      option_Builder6.hasArg();
      option_Builder2.desc("");
      option0.setRequired(false);
      option0.hasValueSeparator();
      option0.setLongOpt("$");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder3.deprecated(deprecatedAttributes0);
      option_Builder5.hasArg(false);
      option0.getLongOpt();
      option0.setValueSeparator('l');
      option0.hasArgs();
      option0.getLongOpt();
      option0.getId();
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Option option0 = new Option("zCcsluw-x", "zCcsluw-x", false, "zCcsluw-x");
      option0.setArgs((-1));
      Converter<?, ?> converter0 = option0.getConverter();
      option0.hasArgs();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.converter(converter0);
      Option.Builder option_Builder2 = option_Builder1.argName("zCcsluw-x");
      Option.Builder option_Builder3 = option_Builder2.required(false);
      Option.Builder option_Builder4 = option_Builder3.required();
      option_Builder4.required();
      Option.Builder option_Builder5 = option_Builder0.valueSeparator('R');
      option_Builder3.optionalArg(false);
      Option.Builder option_Builder6 = option_Builder0.converter(converter0);
      option_Builder6.hasArg();
      option_Builder2.desc("");
      option0.setRequired(false);
      option0.hasValueSeparator();
      option0.setLongOpt("$");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder3.deprecated(deprecatedAttributes0);
      option_Builder5.hasArg(false);
      option0.getLongOpt();
      option0.setValueSeparator('R');
      option0.hasArgs();
      option0.getLongOpt();
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.required();
      Option.builder();
      option_Builder0.required(true);
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('+');
      option_Builder1.hasArg();
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgName("--");
      option0.setArgs((-2));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.getValues();
      option0.setRequired(true);
      option0.toString();
      option0.setRequired(true);
      option0.toDeprecatedString();
      option0.setArgs(3529);
      option0.setRequired(true);
      Class<String> class0 = String.class;
      option0.setType(class0);
      option0.setValueSeparator('c');
      option0.processValue("Option ");
      option0.getSince();
      option0.toDeprecatedString();
      option0.toDeprecatedString();
      Option.builder((String) null);
      int int0 = (-119);
      try { 
        option0.getValue((-119));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(false);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder2.longOpt("");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option0.getDescription();
      option0.hasArgs();
      Option.builder();
      option_Builder6.hasArg(true);
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.toDeprecatedString();
      option0.toString();
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(279);
      Option.Builder option_Builder2 = option_Builder1.longOpt("Empty option name.");
      Option.Builder option_Builder3 = option_Builder2.optionalArg(false);
      Option.Builder option_Builder4 = option_Builder1.hasArgs();
      Class<Object> class0 = Object.class;
      option_Builder1.type(class0);
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder5 = option_Builder3.deprecated(deprecatedAttributes0);
      Option option0 = option_Builder5.get();
      Class<String> class1 = String.class;
      option_Builder1.type(class1);
      deprecatedAttributes0.toString();
      option0.setRequired(false);
      option0.setDescription("value");
      option_Builder3.deprecated(deprecatedAttributes0);
      option0.getValue(279);
      option0.getValue();
      option0.getOpt();
      option_Builder4.numberOfArgs(1);
      Option.Builder option_Builder6 = option_Builder5.optionalArg(false);
      option0.getDescription();
      option0.hasArgs();
      Option.builder();
      option_Builder6.hasArg(true);
      option0.getKey();
      option_Builder6.longOpt("value");
      option0.setType((Object) null);
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgName((String) null);
      Option option1 = (Option)option0.clone();
      Option.builder();
      option1.getValue();
      option0.toDeprecatedString();
      option0.setValueSeparator('k');
      option0.setArgName((String) null);
      option0.getOpt();
      option0.setDescription("");
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator();
      option0.setLongOpt("97U^o=w'x7p>r");
      option0.getValue(61);
      Class<String> class0 = String.class;
      option_Builder0.type(class0);
      option0.setValueSeparator('K');
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      Option option0 = new Option("@", "@");
      option0.getValue("@");
      option0.clone();
      Option.builder();
      option0.clearValues();
      Object object0 = option0.getType();
      option0.equals(object0);
      option0.clearValues();
      option0.setDescription("@");
      option0.setArgs(593);
      Option option1 = (Option)option0.clone();
      Option.builder("@");
      option0.hashCode();
      option0.hashCode();
      option0.setDescription("@");
      option0.getConverter();
      option0.getValueSeparator();
      option0.setLongOpt("");
      option0.isValuesEmpty();
      option0.setOptionalArg(true);
      option0.requiresArg();
      option0.getValueSeparator();
      option0.hasOptionalArg();
      option0.getArgName();
      option0.hasArgName();
      Option option2 = (Option)option0.clone();
      option0.getArgName();
      Option.builder();
      option0.getType();
      option0.isValuesEmpty();
      option0.processValue("@");
      option0.acceptsArg();
      Option.builder();
      option0.getValue("7h={p(al");
      Option option3 = (Option)option1.clone();
      boolean boolean0 = option2.equals(option3);
      assertEquals(593, option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.since((String) null);
      option_Builder0.required(true);
      option_Builder0.optionalArg(true);
      option_Builder0.hasArg(true);
      Option option0 = new Option((String) null, true, " for removal");
      option0.equals(option_Builder0);
      option0.setArgs((-769));
      option0.setDescription("Not yet implemented");
      option0.acceptsArg();
      option0.toString();
      option0.getValuesList();
      option0.setArgName(" for removal");
      option0.getConverter();
      option0.getArgs();
      option0.hasArgName();
      option0.getDeprecated();
      option0.requiresArg();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder1.hasArg();
      option_Builder1.optionalArg(true);
      option_Builder0.argName((String) null);
      option_Builder1.valueSeparator();
      option_Builder0.since((String) null);
      Option option0 = new Option((String) null, false, "^Z#Ls{(");
      option0.clone();
      option0.getValues();
      option0.getValue(1585);
      option_Builder1.required();
      option0.getDeprecated();
      option0.toString();
      // Undeclared exception!
      try { 
        option0.addValue("^Z#Ls{(");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      option0.setValueSeparator('h');
      option0.setArgs(17);
      option0.processValue(":3X]h");
      option0.toDeprecatedString();
      // Undeclared exception!
      try { 
        option0.addValue((String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.hashCode();
      option0.processValue("ZaAjNLA&?*ZKF");
      option0.setRequired(true);
      option0.setValueSeparator('h');
      option0.setLongOpt((String) null);
      // Undeclared exception!
      try { 
        option0.processValue(":3X]h");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      String string0 = null;
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      Option.builder();
      option0.toString();
      option0.setRequired(true);
      option0.setArgs(0);
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.argName((String) null);
      boolean boolean0 = false;
      option_Builder0.deprecated();
      Option.Builder option_Builder1 = option_Builder0.required(false);
      option_Builder1.deprecated();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }
}
