/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 07:55:09 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.SQLTransactionRollbackException;
import org.apache.commons.cli.ParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseException_ESTest extends ParseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnsupportedOperationException unsupportedOperationException0 = new UnsupportedOperationException();
      SQLTransactionRollbackException sQLTransactionRollbackException0 = new SQLTransactionRollbackException(unsupportedOperationException0);
      ParseException parseException0 = new ParseException(sQLTransactionRollbackException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseException parseException0 = new ParseException("org.apache.commons.cli.ParseException");
      ParseException parseException1 = ParseException.wrap(parseException0);
      assertSame(parseException0, parseException1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnsupportedOperationException unsupportedOperationException0 = new UnsupportedOperationException();
      try { 
        ParseException.wrap(unsupportedOperationException0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseException parseException0 = new ParseException("org.apache.commons.cli.ParseException");
      MockIOException mockIOException0 = new MockIOException("org.apache.commons.cli.ParseException", parseException0);
      ParseException parseException1 = ParseException.wrap(mockIOException0);
      assertNotSame(parseException0, parseException1);
  }
}
